language: bash
sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - echo "==> Build with Docker ..."

    - docker build -f test/Dockerfile         -t php7 .         | tee build_result
    - docker build -f test/Dockerfile.centos6 -t php7-centos6 . | tee build_result.centos6
    #- docker build -f test/Dockerfile.debian7 -t php7-debian7 . | tee build_result.debian7
    - docker build -f test/Dockerfile.debian8 -t php7-debian8 . | tee build_result.debian8

script:
    - echo "==> Run Test case ..."

    - grep '00:00:00 php-fpm7.0' build_result
    - grep '00:00:00 php-fpm' build_result.centos6
    #- grep '00:00:00 php-fpm7.0' build_result.debian7
    - grep '00:00:00 php-fpm7.0' build_result.debian8

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

