#!/usr/bin/env ansible-playbook
# vim:ft=ansible :

---

# before install.
- name: Install requires packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - python-apt

- name: Add third-party repository for Debian
  become: true
  apt_repository: >
    repo="deb {{ debian_php7_apt_repo }} {{ ansible_distribution_release }} all"
    state=present
  when: ansible_distribution|lower == "debian"

- name: Add apt key for Debian
  become: true
  apt_key: url={{ debian_php7_apt_key }} state=present
  when: ansible_distribution|lower == "debian"

- name: Add third-party repository for Ubuntu
  become: true
  apt_repository: repo={{ ubuntu_php7_ppa_repo }}
  when: ansible_distribution|lower == "ubuntu"

# Update apt cache.
- name: Update apt cache
  become: true
  apt: update_cache=true

# Install PHP7 packages.
- name: Install PHP Packages
  become: true
  apt: name={{ item }} state=latest
  with_nested: "{{ apt_php_packages }}"
  when: apt_php_packages is defined
  notify:
    - restart php7-fpm

